spring.application.name=MyEnterpriseOpenSource
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.flyway.enabled=true
spring.jpa.show-sql=false
app.security.jwt.issuer=${JWT_ISSUER}
app.security.jwt.private-key-location=${JWT_PRIVATE_KEY_LOCATION}
app.security.jwt.public-key-location=${JWT_PUBLIC_KEY_LOCATION}
app.security.bootstrap.enabled=${APP_SECURITY_BOOTSTRAP_ENABLED:false}
