server.address=127.0.0.1
spring.docker.compose.file=compose.local.yaml
spring.docker.compose.lifecycle-management=start-and-stop
spring.docker.compose.readiness.timeout=3m
app.demo.seed.enabled=${APP_DEMO_SEED_ENABLED:true}
app.registration.code=${APP_REGISTRATION_CODE:local-development-registration-code}
