spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.docker.compose.enabled=false
app.security.jwt.issuer=${JWT_ISSUER}
app.security.jwt.private-key-location=${JWT_PRIVATE_KEY_LOCATION}
app.security.jwt.public-key-location=${JWT_PUBLIC_KEY_LOCATION}
