ALTER TABLE app_user ADD COLUMN active BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE app_user ADD COLUMN token_version INT NOT NULL DEFAULT 0;
ALTER TABLE app_user ADD COLUMN failed_login_attempts INT NOT NULL DEFAULT 0;
ALTER TABLE app_user ADD COLUMN locked_until TIMESTAMP NULL;
